version: '3'
services:
  # NGLoverlay
  sprintoverlay-prod:
    image: sprintoverlay-prod:${NGLOVERLAY_TAG}
    # mount host folder with files as read-only
    volumes:
      - ${FILE_DIR}:/usr/share/nginx/html/pdb:ro
  # SSDB
  ssdb-prod:
    image: ssdb-prod:${SSDB_TAG} 
    # mount host folder with the sqlite3 database, read-only
    volumes:
      - ${DB_DIR}:/app/database:ro
  # reverse proxie
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - 80:80
    volumes:
      - ${NGINX_CONF}:/etc/nginx/nginx.conf:ro